import Nav from "@/components/soundemote/Nav";
import StarField from "@/components/soundemote/StarField";
import Footer from "@/components/soundemote/Footer";

const notThis = [
  "Not a DAW with video bolted on.",
  "Not a VJ tool with audio tacked on.",
  "Not a node-based programming environment that asks the artist to build the instrument first.",
  "Not another split workflow where music, visuals, cameras, and export live in separate mental models.",
];

const whatItIs = [
  "An Audio Visual Workstation where sound and image are equal creative partners.",
  "A visual modular audio workspace for native music systems, visual systems, shader instruments, and audio-reactive visuals.",
  "A music-first creative surface where video, shaders, cameras, and motion can be composed like instruments.",
  "A low-friction workflow for making music you can see.",
];

const compositionModel = [
  "Every beat can have a sound, an image, a motion, and a light.",
  "Audio, video, shaders, cameras, modulation, and export belong to the same composition.",
  "Visuals are not an add-on, preview track, plug-in hack, or separate performance layer.",
  "The system starts with sound and continues into energy, motion, and image.",
];

const immediatePlan = [
  "Focus soemdsp sandbox on browsing synthesizers, effects, and visualizers instead of browsing raw modules.",
  "Create a preset browser as the primary creative doorway.",
  "Keep the module browser available as a deeper backend feature for builders and advanced users.",
  "Let presets become the friendly surface: complete instruments, complete effects, complete visual systems, and curated starting points.",
];

const audiences = [
  {
    title: "For Teachers",
    body:
      "Patches can be sequenced like lesson plans. A class can move from oscillator basics to harmonics, additive synthesis, envelopes, filters, timing, video signals, shader parameters, and mathematical motion while hearing and seeing each concept unfold.",
  },
  {
    title: "For Kids",
    body:
      "Made to be easy to use, sonically interesting, and visually alive. Ear protection and speaker protection are built in, and the audio and video are generated by inspectable algorithms, not by AI audio or video generators.",
  },
  {
    title: "For Mathematicians",
    body:
      "Soundemote can become a living math surface: waves, attractors, modulation, feedback, curves, timing, phase, geometry, and signal flow made audible, visible, and explorable inside the same instrument. Even controls are calculators, such as typing 220 / 2 into a slider and getting 110.",
  },
  {
    title: "For Social Media Creators",
    body:
      "Direct-to-audio and direct-to-video buttons should make sharing feel immediate. Make a beat, watch it move, customize the UI, change the oscilloscope look and feel, and export the audiovisual moment without fighting a separate editor.",
  },
  {
    title: "For Sample Library Creators",
    body:
      "The engine can support advanced infrastructure for one-button multilayer sample library creation: generate variations, capture layers, organize exports, and turn beautiful DSP systems into reusable creative packs.",
  },
  {
    title: "For Plugin Developers",
    body:
      "Built from the ground up for audio plugin development, with CLAP hosting, metaparameters, mixed and manipulated multipoint graphs, in-out-in feedback routing, and anything-to-anything modulation, including audio modulating video and planned video modulating audio.",
  },
  {
    title: "For VJs And Shader Artists",
    body:
      "Shader code editing, audio-controlled shader parameters, camera motion, and screen behavior belong beside the sound. Hear the hit and see the screen shake at the same time, because both events come from one composition.",
  },
];

const AVWResearch = () => (
  <main className="relative z-10 min-h-screen text-foreground">
    <StarField />
    <Nav />
    <section className="relative overflow-hidden px-6 py-20 md:py-28">
      <div className="absolute inset-0 scope-grid opacity-30" aria-hidden />
      <div className="container relative max-w-4xl">
        <p className="mono text-xs uppercase tracking-[0.22em] text-scope">audio visual workstation</p>
        <h1 className="display mt-5 max-w-3xl text-4xl font-semibold leading-tight text-warm-white md:text-6xl">
          Soundemote Sandbox is Pretty Modular
        </h1>
        <p className="display mt-5 max-w-4xl text-2xl font-semibold leading-tight text-scope md:text-5xl">
          A beautiful audio visual workstation where sound, oscilloscopes, shaders, and motion are part of
          the instrument.
        </p>
        <p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">
          Soundemote is building an Audio Visual Workstation where sound and image are equal creative
          partners. Music sequencing, visual sequencing, shader instruments, camera motion, modulation,
          and export belong inside one low-friction creative workflow, with analog-emulated audio
          modules and accurate phosphor oscilloscope simulation designed to look beautiful while staying
          easy to use.
        </p>
        <p className="mt-5 max-w-3xl text-base leading-7 text-muted-foreground">
          The idea starts with the appeal of a pretty oscilloscope and expands it into the whole
          workstation: the controls, graphs, meters, patch cables, oscilloscopes, and exports should be useful
          enough for real work and beautiful enough to become part of the artwork.
        </p>
        <p className="mt-5 max-w-3xl text-base leading-7 text-muted-foreground">
          Sound and image are generated by beautiful algorithms, most of which can be explored inside
          the on-screen manual. The manual is not just documentation; it is part lab notebook, part
          instrument guide, and part map of the mathematics behind the work.
        </p>
        <p className="mt-5 max-w-3xl text-base leading-7 text-muted-foreground">
          The control language is inspired by analog modular instruments: 0.1v/octave oscillators,
          multi-waveform audio outputs, reset inputs, and vactrol-style light-controlled modules with
          LEDs that make the signal feel visible as well as audible.
        </p>
        <p className="mt-5 max-w-3xl text-base leading-7 text-muted-foreground">
          Imagine routing a module back into itself and it just works, then seeing the effect of chaotic
          feedback.
        </p>
      </div>
    </section>

    <section className="px-6 pb-16">
      <div className="container grid gap-6 md:grid-cols-2">
        <article className="rounded-lg border border-border/60 bg-card/70 p-6 shadow-[var(--shadow-panel)]">
          <h2 className="display text-2xl font-semibold text-warm-white">The Core Idea</h2>
          <p className="mt-4 text-base leading-7 text-muted-foreground">
            Not a DAW with video bolted on. Not a VJ tool with audio tacked on. An Audio Visual
            Workstation where music and visuals are composed together from the first beat, with analog
            character treated as part of the instrument instead of a decoration.
          </p>
        </article>

        <article className="rounded-lg border border-border/60 bg-card/70 p-6 shadow-[var(--shadow-panel)]">
          <h2 className="display text-2xl font-semibold text-warm-white">Analog Beauty</h2>
          <p className="mt-4 text-base leading-7 text-muted-foreground">
            Analog-modeled modules, oscilloscope phosphor behavior, glowing signal paths, and a calm
            interface are built together so the workstation feels alive, readable, and inviting.
            LEDs, reset inputs, multi-waveform outputs, and light-controlled behavior are part of the
            visual language, not hidden implementation details.
          </p>
        </article>
      </div>
    </section>

    <section className="px-6 pb-20">
      <div className="container grid gap-8 lg:grid-cols-[1fr_1fr_1fr]">
        <div>
          <h2 className="mono text-sm uppercase tracking-[0.18em] text-scope">what it is not</h2>
          <ul className="mt-5 space-y-4 text-sm leading-7 text-muted-foreground">
            {notThis.map((item) => (
              <li key={item} className="border-l border-border/70 pl-4">
                {item}
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h2 className="mono text-sm uppercase tracking-[0.18em] text-scope">what it is</h2>
          <ul className="mt-5 space-y-4 text-sm leading-7 text-muted-foreground">
            {whatItIs.map((item) => (
              <li key={item} className="border-l border-border/70 pl-4">
                {item}
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h2 className="mono text-sm uppercase tracking-[0.18em] text-scope">composition model</h2>
          <ul className="mt-5 space-y-4 text-sm leading-7 text-muted-foreground">
            {compositionModel.map((item) => (
              <li key={item} className="border-l border-border/70 pl-4">
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>

    <section className="px-6 pb-20">
      <div className="container">
        <p className="mono text-xs uppercase tracking-[0.22em] text-scope">who it opens doors for</p>
        <h2 className="display mt-4 max-w-3xl text-3xl font-semibold leading-tight text-warm-white md:text-4xl">
          One workstation, many ways to learn and publish
        </h2>
        <div className="mt-8 grid gap-5 md:grid-cols-2">
          {audiences.map((audience) => (
            <article key={audience.title} className="rounded-lg border border-border/60 bg-card/70 p-6 shadow-[var(--shadow-panel)]">
              <h3 className="display text-xl font-semibold text-warm-white">{audience.title}</h3>
              <p className="mt-4 text-sm leading-7 text-muted-foreground">{audience.body}</p>
            </article>
          ))}
        </div>
      </div>
    </section>

    <section className="px-6 pb-20">
      <div className="container rounded-lg border border-scope/30 bg-scope/10 p-6 shadow-[var(--shadow-panel)] md:p-8">
        <p className="mono text-xs uppercase tracking-[0.22em] text-scope">immediate plan</p>
        <h2 className="display mt-4 text-3xl font-semibold text-warm-white">
          Presets first, modules behind the curtain
        </h2>
        <p className="mt-4 max-w-3xl text-base leading-7 text-muted-foreground">
          The front of soemdsp sandbox should feel like browsing playable creative systems, not sorting
          through engineering parts. Synthesizers, effects, and visualizers become the main experience.
        </p>
        <ul className="mt-6 grid gap-4 text-sm leading-7 text-muted-foreground md:grid-cols-2">
          {immediatePlan.map((item) => (
            <li key={item} className="border-l border-scope/40 pl-4">
              {item}
            </li>
          ))}
        </ul>
      </div>
    </section>
    <Footer />
  </main>
);

export default AVWResearch;
